#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh checkout || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: deis:checkout. ***"' ERR

set -eo nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

checkout-deis "${DEIS_ROOT}" "${VERSION}"
