#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh clients || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
} 

trap 'rerun_die $? "*** command failed: clients:setup. ***"' ERR

set -eo nounset -o pipefail

rerun_options_parse "$@"

source-defaults

load-env

source-config

setup-clients "${VERSION}"
