#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh test || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: deis:test. ***"' ERR

set -eo nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

setup-ssh-agent

setup-test-hacks

(
  cd ${DEIS_ROOT}

  case "${TYPE}" in
    scaleup)
      for i in $(seq 1 5); do
        deis scale web=10
        sleep 3
        deis scale web=0
        sleep 3
      done
      ;;
    *)
      make test-${TYPE}
      ;;
  esac
)
