# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Fri Aug 21 09:59:51 MDT 2015
#
#/ usage: deis:provision  --provider <vagrant> [ --version <master>] [ --cleanup] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --provider) rerun_option_check $# $1; PROVIDER=$2 ; shift ;;
            --version) rerun_option_check $# $1; VERSION=$2 ; shift ;;
            --cleanup) CLEANUP=true; [[ ${2:-} == true ]] && shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$PROVIDER" ] && PROVIDER="$(rerun_property_get $RERUN_MODULE_DIR/options/provider DEFAULT)"
    [ -z "$VERSION" ] && VERSION="$(rerun_property_get $RERUN_MODULE_DIR/options/version DEFAULT)"
    [ -z "$CLEANUP" ] && CLEANUP="$(rerun_property_get $RERUN_MODULE_DIR/options/cleanup DEFAULT)"
    # Check required options are set
    [ -z "$PROVIDER" ] && { echo >&2 "missing required option: --provider" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${PROVIDER:=}
: ${VERSION:=}
: ${CLEANUP:=}


