#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh provision || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: provision. ***"' ERR

set -eo nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

setup-provider "${PROVIDER}"

setup-provider-dependencies

load-env "${RIGGER_VARS_FILE}"

setup-clients "${VERSION}"

(
  cd ${DEIS_ROOT}
  make discovery-url
)

setup-ssh-agent

create-cluster

rigger deploy
