#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh upgrade || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: tests:upgrade. ***"' ERR

set -eo nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

trap destroy-cluster EXIT

setup-upgrader "${UPGRADE_STYLE}"

save-vars UPGRADE_STYLE

setup-ssh-agent

upgrade-deis "${VERSION}" "${TO}"

healthcheck-app "testing"
