#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh destroy || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: deis:destroy. ***"' ERR

set -eo nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

setup-provider "${PROVIDER}"

destroy-cluster true
