#!/usr/bin/env bash

. $RERUN_MODULE_DIR/lib/functions.sh deploy || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

trap 'rerun_die $? "*** command failed: deploy. ***"' ERR

set -eo nounset -o pipefail

source-defaults

load-env

rerun_options_parse "$@"

source-config

setup-provider "${PROVIDER}"

setup-ssh-agent

load-env "${RIGGER_VARS_FILE}"

build-deis "${VERSION}"

deploy-deis "${VERSION}"
